"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.NotionImportTaskInputItemSchema = exports.NotionImportInputItemSchema = exports.MarkdownImportInputItemSchema = exports.MarkdownAttachmentManifestItemSchema = exports.JSONImportInputItemSchema = exports.JSONAttachmentManifestItemSchema = exports.IssueSource = exports.BaseImportTaskInputItemSchema = void 0;
var _zod = require("zod");
var _types = require("./types");
var _types2 = require("../plugins/notion/shared/types");
const BaseImportInputItemSchema = _zod.z.object({
  permission: _zod.z.enum(_types.CollectionPermission).optional()
});
const NotionImportInputItemSchema = exports.NotionImportInputItemSchema = BaseImportInputItemSchema.extend({
  type: _zod.z.enum(_types2.PageType).optional(),
  externalId: _zod.z.string().optional()
});
const MarkdownImportInputItemSchema = exports.MarkdownImportInputItemSchema = BaseImportInputItemSchema.extend({
  externalId: _zod.z.string()
});
const JSONImportInputItemSchema = exports.JSONImportInputItemSchema = BaseImportInputItemSchema.extend({
  externalId: _zod.z.string()
});
const BaseImportTaskInputItemSchema = exports.BaseImportTaskInputItemSchema = _zod.z.object({
  externalId: _zod.z.string(),
  parentExternalId: _zod.z.string().optional(),
  collectionExternalId: _zod.z.string().optional()
});
const NotionImportTaskInputItemSchema = exports.NotionImportTaskInputItemSchema = BaseImportTaskInputItemSchema.extend({
  type: _zod.z.enum(_types2.PageType)
});
/**
 * Manifest entry describing a single attachment discovered during the
 * Markdown zip bootstrap phase. The `id` is a pre-assigned UUID used both
 * as the attachment node id in per-page prosemirror output and as the
 * Attachment row id created during completion.
 */
const MarkdownAttachmentManifestItemSchema = exports.MarkdownAttachmentManifestItemSchema = _zod.z.object({
  id: _zod.z.uuid(),
  name: _zod.z.string(),
  mimeType: _zod.z.string(),
  pathInZip: _zod.z.string()
});

/**
 * Markdown importer scratch state. `storageKey` is set at import creation
 * (it's the only durable handle on the uploaded zip). `manifest` is added
 * by the bootstrap phase so the completion phase can re-download the zip
 * and create Attachment rows without re-walking the tree.
 */

/**
 * Manifest entry describing a single attachment discovered during the JSON
 * zip bootstrap phase. `externalId` is the attachment's original id from the
 * export — used to rewrite `/api/attachments.redirect?id=<externalId>`
 * references in document/collection content into new redirect URLs that point
 * at the freshly created Attachment row (`id`).
 */
const JSONAttachmentManifestItemSchema = exports.JSONAttachmentManifestItemSchema = _zod.z.object({
  id: _zod.z.uuid(),
  externalId: _zod.z.string(),
  name: _zod.z.string(),
  mimeType: _zod.z.string(),
  pathInZip: _zod.z.string()
});

/**
 * JSON importer scratch state. `storageKey` is set at import creation (it's
 * the only durable handle on the uploaded zip). `manifest` is added by the
 * bootstrap phase so the completion phase can re-download the zip and create
 * Attachment rows without re-parsing the JSON files.
 */

/**
 * Per-importer scratch shape stored on `Import.scratch`. Holds cross-phase
 * state that the importer needs between bootstrap and completion but that
 * isn't part of any single task's input. Cleared when the import flips to
 * `Processed`.
 */

/**
 * Per-page task input. Generated by the bootstrap task and consumed by
 * subsequent MarkdownAPIImportTask runs. `children` carries this document's
 * direct descendants so that each level of the document tree is scheduled
 * as a separate task wave; this preserves parent-before-child ordering
 * during persistence (createdAt of child tasks is strictly later than
 * parents'). The type is defined as a TypeScript interface rather than via
 * z.infer because it is only consumed internally — never validated at an
 * API boundary — and zod's recursive-schema ergonomics aren't worth the
 * cost here.
 */

/**
 * Markdown import task input — a bootstrap row carrying only the base
 * placeholder item (the zip's `storageKey` lives on `Import.scratch`), or a
 * page row carrying per-document content.
 */

/**
 * Per-page task input for the JSON importer. Generated by the bootstrap task
 * once the zip has been parsed; consumed by subsequent JSONAPIImportTask runs.
 * `children` carries this document's direct descendants so each tree-depth
 * runs as its own task wave, preserving parent-before-child ordering during
 * persistence (createdAt of child tasks is strictly later than parents'). The
 * type is defined as a TypeScript interface rather than via z.infer because
 * it is only consumed internally — never validated at an API boundary — and
 * zod's recursive-schema ergonomics aren't worth the cost here.
 */

/**
 * JSON import task input — a bootstrap row carrying only the base placeholder
 * item (the zip's `storageKey` lives on `Import.scratch`), or a page row
 * carrying per-document content.
 */

// No reason to be here except for co-location with import task input.

const IssueSource = exports.IssueSource = _zod.z.object({
  id: _zod.z.string().nonempty(),
  name: _zod.z.string().nonempty(),
  owner: _zod.z.object({
    id: _zod.z.string().nonempty(),
    name: _zod.z.string().nonempty()
  }),
  service: _zod.z.enum(_types.IssueTrackerIntegrationService)
});